### ISSUE TITLE
Getting IDBIndex Not Defined Error

### ISSUE THREAD

**Issue by alteredorange** [lpshanley/routify-starter-firebase#2]
Hello! I was playing around with this this morning and it looks like SSR has trouble using all of the firebase imports. It throws an IDBIndex is not defined. (It also throws openDB and deleteDb not defined, but those are fixed by adding them as named exports in commonjs).  Here's my firebaseinit.js:

`var firebase = require("firebase/app");
require("firebase/auth");
require("firebase/firestore");
require("firebase/analytics");
require("firebase/storage");
require("firebase/messaging");

const firebaseConfig = {....};
firebase.initializeApp(firebaseConfig);

export let auth = firebase.auth();
export let storage = firebase.storage();
export let fs = firebase.firestore();
export let ana = firebase.analytics();
export let messaging = firebase.messaging();`

and then in index.svelte:

`<script>
  import { auth, messaging, fs, storage, ana } from "./firebaseinit.js";
</script>`

**Comment by lpshanley** [comment]
The SSR utility that Routify uses is called JSDOM, this emulates the browser in the node.js environment. Node.js by default does not actually have built in features for IndexedDB is this a DOM only utility. You actually don't want things like analytics or perf monitoring when you are in SSR because every page view would technically count as two and the location on the first would always be your SSR servers.

What I use to solve this is to create a readable store that will return a boolean to tell my code if I am running in SSR or not.

I call this file ssr.js
 ```js
// ssr.js
import { readable } from 'svelte/store'

const SSR_ENV = navigator.userAgent.includes("Node.js") || navigator.userAgent.includes("jsdom")

export const SSR = readable(SSR_ENV)
```

Lets say that I am now i am intending to integrate something that I would only like to render on the user side, not in ssr.
One way that I have done this in the past might look like this (google-maps example)
```js
// google-maps.js
import { writable } from 'svelte/store'

const isSSR = navigator.userAgent.includes("Node.js") || navigator.userAgent.includes("jsdom")
const MapsReady = writable(false)
const MapsKey = {}

const API_TOKEN = "your_client_side_api_key_here"

const GoogleMaps = document.createElement('script')
GoogleMaps.defer = true
GoogleMaps.async = true

window.initMap = () => MapsReady.set(true)
GoogleMaps.src = `https://maps.googleapis.com/maps/api/js?key=${API_TOKEN}&callback=initMap`

if(!isSSR) document.head.appendChild(GoogleMaps)

export { MapsReady, MapsKey }
```

You might not need the maps key, I use it to create a pin component and reference the [Context API](https://svelte.dev/tutorial/context-api).
